config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    collection do
      get 'dashboard', to: 'users#dashboard', as: :dashboard
    end
  end

  resources :events do
    resources :fees, only: [:create, :index, :update, :destroy]
    get '/:token/invitation', to: 'events#invitation', as: :invitation
    resources :contributions, only: [:index, :create, :destroy, :update]
    resources :participations, only: [:index, :update, :destroy, :create]
    resources :supplies, only: [:index, :create, :update, :destroy]
    resources :fee_contributions, only: [:destroy, :create]
  end
  

  resources :contributions, only: [] do
    post 'change-state', to: 'contributions#change_state'
  end
  

  # static pages
  get "/composants" => "pages#composants"

end

app/views/shared/_card.html.erb
<div class="card-event">
	<div class="picture">
		<%= event.picture.url.nil? ? image_tag("default-event.jpg") : cl_image_tag(event.picture, crop: :fill)  %>
		<h4><%= event.title %></h4>
		<div class="pelette">
			<div class="date">
				<div class="p day"><%= event.start_date.strftime("%d") %></div>
				<div class="p month"><%= l(event.start_date, format: :month) %></div>
			</div>
		</div>
	</div>
	<div class="infos">
		<div class="contributions">
			<h4>Vous apportez :</h4>
			<ul>
      <% contributions = event.participations.where(user_id: current_user)[0].contributions %>
        <% contributions.first(3).each do |contribution| %>
        <li> - <%= contribution.supply.title %></li>
        <% end %>
        <% if contributions.size > 3 %>
        <li>- ...</li>
        <% end %>
			</ul>
		</div>
		<div class="supplies">
			<% @categories.each do |category| %>
				<span class="badge-pill badge badge-dark">
					<i class="<%= category.icon %>"></i>
					<%=  category.category_supplies(event).size - category.status(event) %>
				</span>
			<% end %>
		</div>
		<div class="guests">
			<div class="img">
				<% event.participations.first(4).each do |participant| %>
					<%= participant.user.avatar.url.nil? ? image_tag("person-dummy.jpg", options = {class: "avatar-bordered"}) :  cl_image_tag(participant.user.avatar, options = {class: "avatar-bordered"}) %>
				<% end %>
			</div>
			<p> <%= event.participations.size %> participant(s) </p>
		</div>
	</div>
	<div class="organizer">
		<%= event.user.avatar.url.nil? ? image_tag("person-dummy.jpg", options = {class: "avatar-bordered"}) :  cl_image_tag(event.user.avatar, options = {class: "avatar-bordered"}) %>
	</div>
</div>

app/views/shared/_event_header.html.erb
<div id="event-header" style="background-image: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.5)), 
  url('<%= @event.picture.url.nil? ? asset_url("default-event.jpg") :  cl_image_path(@event.picture) %>');">
  <div class="container">
    <div>
      <h2><%= event.title %></h2>
      <p>
        <i class="far fa-calendar-alt"></i> 
        <%= l(event.start_date, format: :custom).capitalize %>   <%= "au #{l(event.end_date, format: :custom)}" if event.end_date > event.start_date %>
      </p>
      <p><i class="fas fa-map-marked-alt"></i>   <%= event.address %> à <%= event.city %></p>
    </div>
    <div class="map d-flex flex-column justify-content-start">
    <%= link_to("https://www.google.com/maps/search/#{map_url}", target: "_blank") do %>
      <span class="fa-stack fa-2x mb-2">
      <i class="fas fa-circle fa-stack-2x"></i>
      <i class="fas fa-map-marked-alt fa-stack-1x fa-inverse"></i>
      </span>
    <%end%>
    <%= link_to(agenda_url, target: "_blank") do %>
      <span class="fa-stack fa-2x mb-2">
      <i class="fas fa-circle fa-stack-2x"></i>
      <i class="fas fa-calendar-alt fa-stack-1x fa-inverse"></i>
      </span>
    <%end%>
    </div>
  </div>
  <% if current_user == event.user %>
    <div class="container">
        <%= link_to event_path(event), method: :delete, data: { confirm: "L'évènement va être supprimé !" }, class: "btn-base btn-danger btn-thin" do %>
          Annuler l'évènement
        <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-expand-lg">
  <div class="container">
  <ul class="navbar-events navbar-nav">
    <div>
      <%= link_to events_path do %>
        <i class="fas fa-home" style="font-size: 25px"></i>
      <% end %>
    </div>
    <li id="item-participations" class="nav-item">
      <%= link_to 'Invités', event_participations_path(@event) %>
    </li>
    <li id="item-details" class="nav-item">
      <%= link_to 'Détails', event_path(@event) %>
    </li>
    <li id="item-list" class="nav-item">
      <%= link_to 'Ma liste', event_contributions_path(@event) %>
    </li>
    <li id="item-frais" class="nav-item">
      <%= link_to 'Frais', event_fees_path(@event) %>
    </li>
    <li class="nav-item dropdown dropleft">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.avatar.nil? || current_user.avatar.blank? ? image_tag("person-dummy.jpg", size: "40", class: "avatar") : cl_image_tag(user.avatar, class: "avatar") %> 
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "Modifier mon profile", edit_user_registration_path, class: "dropdown-item text-dark" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item text-dark" %>
      </div>
    </li>
  </ul>
  </div>
</nav>

app/views/shared/_to_do.html.erb
<section class="todo">
	<h2>Ma liste :</h2>
	<ul class="todo-list">
		<% if contributions.empty? %>
			<li>Vous n'avez encore rien dans votre liste</li>
		<% else %>
			<% contributions.each do |contribution| %>
				<% if contribution.supply.event.id == @event.id %>
					<% id = contribution.id %>
					<% if contribution.state && contribution.part > 0 %>
						<li>
							<input type="checkbox" id="<%= id %>" checked/>
							<label class="toggle" for="<%= id %>"></label>
							<%= "#{contribution.part} x " if contribution.supply.quantity > 1 %>
							<%= contribution.supply.title %>
						</li>
					<% elsif contribution.part > 0 %>
						<li>
							<input type="checkbox" id="<%= id %>"/>
							<label class="toggle" for="<%= id %>"></label>
							<%= "#{contribution.part} x " if contribution.supply.quantity > 1 %>
							<%= contribution.supply.title %>
						</li>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
	</ul>
</section>