config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    collection do
      get 'dashboard', to: 'users#dashboard', as: :dashboard
    end
  end

  resources :events do
    resources :fees, only: [:create, :index, :update, :destroy]
    get '/:token/invitation', to: 'events#invitation', as: :invitation
    resources :contributions, only: [:index, :create, :destroy, :update]
    resources :participations, only: [:index, :update, :destroy, :create]
    resources :supplies, only: [:index, :create, :update, :destroy]
    resources :fee_contributions, only: [:destroy, :create]
  end
  

  resources :contributions, only: [] do
    post 'change-state', to: 'contributions#change_state'
  end
  

  # static pages
  get "/composants" => "pages#composants"

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :participations, dependent: :destroy
  has_many :supplies, dependent: :destroy
  has_many :users, through: :participation
  has_many :contributions, through: :participation
  has_many :fees, through: :participations

  validates :title, :address, :city, :zipcode, :start_date, :end_date, presence: true
  validates :start_date, :end_date, inclusion: { in: (Date.today..Date.today+1.years), message: "Invalid date" }
  mount_uploader :picture, PhotoUploader

  def agenda_url
    text = title.split(" ").join("+")
    details = self.description.split(" ").join("+")
    location = (self.address.split(" ") + self.city.split(" ")).join("+")
    first_day = "#{self.start_date.year}#{self.start_date.strftime("%m")}#{self.start_date.strftime("%d")}"
    self.end_date = self.start_date if self.end_date.blank? || self.end_date.nil?
    last_date = self.end_date + 1.day
    last_day = "#{last_date.year}#{last_date.strftime("%m")}#{last_date.strftime("%d")}"
    agenda_url = "https://www.google.com/calendar/render?action=TEMPLATE&text=#{text}&details=#{details}&location=#{location}&dates=#{first_day}%2F#{last_day}"
  end

  def map_url
    (address.split(" ") + city.split(" ")).join("+")
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find(params[:id])
    @map_url = @event.map_url
    @agenda_url = @event.agenda_url
    @title = @event.title
    authorize @event
    @categories = Category.all
    @participation = Participation.find_by(user_id: current_user.id, event_id: @event.id)
    @contributions = @participation.contributions
    @contribution = Contribution.new
  end

  def index
    @events = policy_scope(Event)
    @categories = Category.all
    @user_events = @events.where(user: current_user).map { |event| event if DateTime.now.to_date < event.end_date }
    @attending = Participation.where(user: current_user, organizer: false).map { |participation| participation.event if DateTime.now.to_date <= participation.event.end_date }
    @finish = Participation.where(user: current_user).map do |participation|
      participation.event if DateTime.now.to_date > participation.event.end_date
    end
    @user_events.compact!
    @attending.compact!
    @finish.compact!
    @title = "Mes événements"
  end

  def new
    @event = Event.new
    @event.user = current_user
    authorize @event
    @title = "Créer ton nouvel événement"
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.token = (0...10).map { (65 + rand(26)).chr }.join
    authorize @event
    if @event.save
      Participation.create!(
        confirmed: true,
        event_id: @event.id,
        user_id: @event.user.id,
        organizer: true
      )
      # mail = EventMailer.with(event: @event).create_confirmation
      # mail.deliver_now
      redirect_to events_path
    else
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])
    authorize @event
    @event.destroy
    redirect_to events_path
  end

  def invitation
    @event = Event.find(params[:event_id])  
    redirect_to event_path(@event) if (@event.participations & current_user.participations).present?
    @map_url = @event.map_url
    @agenda_url = @event.agenda_url
    authorize @event
    @participation = Participation.new
    @title = "Invite tes amis"
  end

  private

  def event_params
    params.require(:event).permit!
  end

end

app/views/events/_supply_card.html.erb
<% contribute = @participation.contributions.where("supply_id = #{supply.id}") %>
<% contribute_part = 0 %>
<div class="supply-card">
  <strong><%= supply.quantity %> <%= supply.title %></strong>
  <p><%= rest %> restants</p>
  <% if contribute.first != nil %>
    <% contribute.each { |c| contribute_part += c.part } %>
    <p class="text-danger">J'en prend déja : <%= contribute_part %></p>
  <% end %>
  <% if rest <= 0 %>
    <p class="text-success">completed</p>
  <% else %>

    <form action="<%= event_contributions_path(@event) %>" method="POST">
      <label for="part">J'en prend</label>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= hidden_field_tag :participation_id, @participation.id %>
      <%= hidden_field_tag :supply_id, supply.id %>
      <select name="part">
        <% (1..supply.rest).to_a.each do |nb| %>
          <option value="<%= nb %>"><%= nb %></option>
        <% end %>
      </select>
      <input type="submit" value="Go!" class="btn-thin btn-base btn-blue">
    </form>

  
    
  <% end %>
</div>

app/views/events/index.html.erb
<% content_for :meta_title, "Mes événements" %>

<div class="event-container">
  <div class="event-banner">
  <div class="container align-items-center d-flex justify-content-between">
    <h1>Bonjour <%= current_user.first_name %></h1>
    <div class="dropdown dropleft">
      <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.avatar.url.nil? ? image_tag("person-dummy.jpg", options = {class: "avatar-bordered"}) :  cl_image_tag(current_user.avatar, options = {class: "avatar-bordered"}) %>
      </div>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to "Modifier mon profile", edit_user_registration_path, class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
  </div>
  </div>
  
  <div>
    <%= link_to 'Créer un évènement', new_event_path, class:"btn-base btn-blue" %>
  </div>

  

  <div class="separator">
    <h4>J'organise</h4>
  </div>
  <div class="container">  
    <% @user_events.each do |event| %>
      <%= link_to event_path(event) do %>
        <%= render "shared/card", event: event %>
      <% end %>
    <% end %>
  </div>

  <div class="separator">
    <h4>Je participe</h4>
  </div>
  <div class="container">
    <% @attending.each do |event| %>
      <%= link_to event_path(event) do %>
        <%= render "shared/card", event: event %>
      <% end %>
    <% end %>
  </div>

  <div class="separator">
    <h4>Fini(s)</h4>
  </div>
<div class="container">
    <% @finish.each do |event| %>
      <%= link_to event_path(event) do %>
        <%= render "shared/card", event: event %>
      <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/events/invitation.html.erb
<% content_for :meta_title, "Invitation | #{l(@event.start_date, format: :custom).capitalize} | #{@event.title} chez #{@event.user.first_name}" %>
<%= render "shared/event_header", event: @event, map_url: @map_url, agenda_url: @agenda_url %>
<div class="container">
  <div class="description p-3">
    <p><strong>Infos :</strong> <%= @event.description %></p>
    <div class="text-center ml-1">
      <%= cl_image_tag @event.user.avatar, height: 30, width: 30, crop: :fill, class: "avatar" %>
      <p><%= @event.user.first_name %></p>
    </div>
  </div>

  <%= simple_form_for [@event, @participation] do |f| %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= hidden_field_tag :user_id, current_user.id %>
    <%= hidden_field_tag :event_id, @event.id %>
    <%= f.button :submit, "Je participe !", class:"btn-base btn-blue btn-large" %>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="new">

    <h1>Créer un événement</h1>

    <div>
      <%= simple_form_for [@event] do |f| %>
        <div class="form-inputs text-center">
            <%= f.input :title,
                        placeholder: "Titre de l'événement",
                        label: false,
                        required: true,
                        autofocus: true %>
            <%= f.input :address,
                        placeholder: "Adresse",
                        label: false,
                        required: true,
                        autofocus: true %>
            <%= f.input :zipcode,
                        placeholder: "Code postal",
                        label: false,
                        required: true,
                        autofocus: true %>
            <%= f.input :city,
                        placeholder: "Ville",
                        label: false,
                        required: true,
                        autofocus: true %>
            <%= f.input :start_date,
                        as: :string,
                        placeholder: "Date début",
                        label: false,
                        required: true,
                        autofocus: true,
                        input_html: { class: "datepicker" } %>
            <%= f.input :end_date,
                        as: :string,
                        placeholder: "Date fin",
                        label: false,
                        required: true,
                        autofocus: true,
                        input_html: { class: "datepicker" } %>
            <%= f.input :description,
                        placeholder: "Description",
                        label: false,
                        required: true,
                        autofocus: true %> 
            <label class="file optional" for="event_picture"><i class="fas fa-file-image fa-5x"></i><br />Ajouter une photo</label>
            <%= f.input :picture_cache, as: :hidden %>
            <%= f.input :picture, label: false %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, "Créer l'événement", class:"btn-base btn-blue btn-large" %>
        </div>
      <% end %>
    </div>
</div>  

app/views/events/show.html.erb
<% content_for :meta_title, "#{l(@event.start_date, format: :custom).capitalize} | #{@event.title} chez #{@event.user.first_name}" %>

<%= render "shared/navbar", user: current_user %>
<%= render "shared/event_header", event: @event, map_url: @map_url, agenda_url: @agenda_url %>
<div class="container">
  <div class="description p-3">
    <p><i class="fas fa-info-circle"></i>  <%= @event.description %></p>
    <div class="text-center ml-1">      
      <%= @event.user.avatar.nil? || @event.user.avatar.blank? ? image_tag("person-dummy.jpg", size: "30", class: "avatar") : cl_image_tag(@event.user.avatar, class: "avatar", size: "30") %>
      <p><%= @event.user.first_name %></p>
    </div>
  </div>
</div>

<div class="separator">
  <h4>Qui ramène quoi ?</h4>
</div>

<div class="container">
  <div class="list">
    <% @categories.each do |category| %>
      <% supplies = category.category_supplies(@event) %>
      <div class="category">
        <a class="category-title" data-toggle="collapse" href="#<%= category.name %>" role="button" aria-expanded="false" aria-controls="<%= category.name %>">
            <h3><strong><%= category.name %></strong> ( <%= category.status(@event) %> / <%= supplies.size %> )</h3>
            <i class="fas fa-plus"></i>
        </a>
        <div class="category-list collapse" id="<%= category.name %>">
          <% supplies.each do |supply| %>
            <%= render "contributions/supply_card", supply: supply, participation: @participation, contribution: @participation.contributions.find_by(supply_id: supply.id) %>
          <% end %>
          <div class="text-center">
            <button type="button" class="btn-modal btn-base btn-blue" data-category="<%= category.id %>" data-toggle="modal" data-target="#new">
            Ajouter un élèment
            </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div> 

<!-- Modal -->
<div class="modal fade" id="new" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="add modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">X</span>
        </button>
          <h2>Que faut-il de plus ? 🎉</h2>
          <form class="add-stuff" id="modal-form" action="<%= event_supplies_path(@event) %>" method="post" data-category="">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= hidden_field_tag :event_id, @event.id %>
            <input type="hidden" name="category_id" id="category_id" value="0">
            <input class="add-number" type="text" name="title" placeholder="Quoi ?">
            <input class="add-number" type="number" name="quantity" placeholder="Combien ?">
            <input type="submit" value="Ajouter" class="btn-thin btn-base btn-blue">
          </form>
      </div>
    </div>  
  </div>
</div>

<script>
  const activeTab = document.getElementById("item-details")
  activeTab.classList.add("active")

  const refreshJs = (card) => {
    const minus = card.querySelector('.minus');
    const plus = card.querySelector('.plus');
    const partInput = card.querySelector('.part');
    const incrementers = card.querySelectorAll('.incrementer');
    const counter = card.querySelector('.counter');
    const submitContribution = card.querySelector('.submit');
    let count = parseInt(counter.dataset.count, 10);
    const rest = parseInt(counter.dataset.rest, 10) + count;

    const externalFunction = (event) => {
      let count = parseInt(counter.dataset.count, 10);
      const part = count;
      count += parseInt(event.currentTarget.dataset.offset, 10);
      counter.innerHTML = count;
      counter.dataset.count = count;
      partInput.value = count;
      if (count == part) {
        submitContribution.setAttribute('disabled', 'true');
        submitContribution.classList.add('inactive');
      } else { 
        submitContribution.removeAttribute('disabled');
        submitContribution.classList.remove('inactive');
      }
      if (count == rest) {
        plus.setAttribute('disabled', 'true');
      } else { plus.removeAttribute('disabled'); }
      if (count <= 0) {
        minus.setAttribute('disabled', 'true');
      } else { minus.removeAttribute('disabled'); }
    };

    incrementers.forEach((incrementer) => {
      if (count === rest) { plus.setAttribute('disabled', 'true'); }
      if (count <= 0) { minus.setAttribute('disabled', 'true'); } 
      if (true) {
        console.log('adding event listener for the first time');
        incrementer.addEventListener('click', (event) => {
          externalFunction(event);
        });
      };
      
    });
  };
  const cards = document.querySelectorAll('.supply-card');
  cards.forEach((card) => {
    refreshJs(card)
  });
</script>