config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    collection do
      get 'dashboard', to: 'users#dashboard', as: :dashboard
    end
  end

  resources :events do
    resources :fees, only: [:create, :index, :update, :destroy]
    get '/:token/invitation', to: 'events#invitation', as: :invitation
    resources :contributions, only: [:index, :create, :destroy, :update]
    resources :participations, only: [:index, :update, :destroy, :create]
    resources :supplies, only: [:index, :create, :update, :destroy]
    resources :fee_contributions, only: [:destroy, :create]
  end
  

  resources :contributions, only: [] do
    post 'change-state', to: 'contributions#change_state'
  end
  

  # static pages
  get "/composants" => "pages#composants"

end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :supply
  belongs_to :participation
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  skip_after_action :verify_policy_scoped, only: :index
  skip_before_action :verify_authenticity_token, only: :change_state
  skip_after_action :verify_authorized, only: :change_state

  def create
    @supply = Supply.find(params[:supply_id])
    @participation = Participation.find(params[:participation_id])
    @event = Event.find(params[:event_id])
    @contribution = Contribution.new(contribution_params)
    authorize @contribution
    @contribution.save
    respond_to do |format|
      format.html { redirect_to event_path(@event) }
      format.js
    end
  end

  def update
    @participation = Participation.find(params[:participation_id])
    @supply = Supply.find(params[:supply_id])
    @event = Event.find(params[:event_id])
    @contribution = Contribution.find(params[:id])
    @contribution.part = params[:part]
    authorize @contribution
    @contribution.save
    respond_to do |format|
      format.html { redirect_to event_path(@event) }
      format.js
    end
  end

  def index
    @fee = Fee.new
    @event = Event.find(params[:event_id])
    @participation = Participation.find_by(user_id: current_user.id, event_id: @event.id)
    @map_url = @event.map_url
    @agenda_url = @event.agenda_url
    @contributions = @participation.contributions
  end

  def change_state
    contribution = Contribution.find(params[:contribution_id])
    contribution.state = !contribution.state
    contribution.save
  end

  private

  def contribution_params
    {
      part: params[:part].to_i,
      participation_id: params[:participation_id].to_i,
      supply_id: params[:supply_id].to_i
    }
  end
end

app/views/contributions/_supply_card.html.erb
<div class="supply-card" data-supply-id="<%= supply.id %>" data-part="<%= contribution.nil? ? 0 : contribution.part %>">
  <div class="d-flex justify-content-between">
    <strong><%= supply.quantity %> <%= supply.title %></strong>
    <span class="mx-1 text-right">
      <%= link_to event_supply_path(@event, supply), remote: true , method: :delete, data: { confirm: "Êtes vous sûr ?" }, class: "text-decoration-none text-secondary" do %>
        <strong><i class="fas fa-trash"></i></strong>
      <% end %>
    </span>
  </div>
  <div class="d-flex justify-content-between">
    <p style="font-size: 16px; color: <%= supply.rest == 0 ? "green" : "gray" %>; margin: 2px"><%= supply.rest %> restant(s)</p>
    <div class="guests">
      <% supply.contributions.first(4).each do |contribution| %>
        <%= contribution.participation.user.avatar.url.nil? ? image_tag("person-dummy.jpg", options = {class: "avatar", size: "30", style: "margin-left: -10px; border: 1px solid white;"}) :  cl_image_tag(contribution.participation.user.avatar, options = {class: "avatar", size: "30", style: "margin-left: -10px; border: 1px solid white;"}) %>
      <% end %>
		</div>
  </div>
  <div class="actions d-flex align-items-center">
    <span>J'en prends : </span>
    <button class="btn incrementer minus" data-offset="-1"><i class="fas fa-minus-circle"></i></button>
    <span class="counter" data-rest="<%= supply.rest %>" data-count="<%= contribution.nil? ? 0 : contribution.part %>"><%= contribution.nil? ? 0 : contribution.part %></span>
    <button class="btn incrementer plus" data-offset="1"><i class="fas fa-plus-circle"></i></button>
    <% if contribution.nil? %>
      <%= form_for([@event, Contribution.new], remote: true) do %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= hidden_field_tag :participation_id, participation.id %>
        <%= hidden_field_tag :supply_id, supply.id %>
        <input type="hidden" class="part" name="part" value="0">
        <input type="submit" value="Valider" disabled="true" class="submit inactive btn-thin btn-base btn-blue" style="margin: 2px">
      <% end %>
    <% else %>
      <%= form_for([@event, contribution], method: :put, remote: true) do %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= hidden_field_tag :participation_id, participation.id %>
        <%= hidden_field_tag :supply_id, supply.id %>
        <input type="hidden" class="part" name="part" value="0">
        <input type="submit" value="Valider" disabled="true" class="submit inactive btn-base btn-blue btn-thin" style="margin: 2px">
      <% end %>
    <% end %>
  </div>
</div>

app/views/contributions/create.js.erb
function refreshUpdateForm(innerHTML) {
  const supplyCard = document.querySelector("[data-supply-id='<%= @supply.id %>']");
  supplyCard.innerHTML = innerHTML;
  refreshJs(supplyCard);
}
refreshUpdateForm('<%= j render "supply_card", supply: @supply, participation: @participation, contribution: @participation.contributions.find_by(supply_id: @supply.id)%>')

app/views/contributions/index.html.erb
<% content_for :meta_title, "Ma liste de courses | #{l(@event.start_date, format: :custom).capitalize} | #{@event.title} chez #{@event.user.first_name}" %>
<%= render "shared/navbar", user: current_user %>
<%= render "shared/event_header", event: @event, map_url: @map_url, agenda_url: @agenda_url %>

<div class="container">

  <%= render 'shared/to_do', contributions: @contributions %>

  <div class="create-fee">

    <% if @participation.fee.nil? %>
      <h3 class="text-secondary">Participation aux frais :</h3>
      <form action="<%= event_fees_path(@event) %>" method="post">
        <label for="cost">J'ai dépensé :</label>
        <input type="number" name="cost">
        <label for="cost"> €</label>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= hidden_field_tag :participation_id, @participation.id %>
        <%= hidden_field_tag :event_id, @event.id %><br>
        <input type="submit" value="Demander" class="btn-base btn-blue">
      </form>
    <% else %>
      <a class="btn" data-toggle="collapse" href="#modif-form" role="button" aria-expanded="false" aria-controls="modif-form">
        <h3 class="text-secondary">Vous avez dépensé : <br><%= @participation.fee.cost %> €
        <i class="fas fa-edit"></i>
        </h3>
      </a>
      <div class="collapse" id="modif-form">
        <%= form_for([@event, @participation.fee], method: :put) do %>
          <input type="number" name="cost" value="<%= @participation.fee.cost %>">
          <label for="cost"> €</label>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %><br>
          <input type="submit" value="Envoyer" class="btn-base btn-blue">
        <% end %>
        <%= link_to event_fee_path(@event, @participation.fee), method: :delete, class: "btn-base btn-red" do %>
          Ne rien demander
        <% end %>
      </div>
    <% end %>

  </div>

</div>

<script>
  const activeTab = document.getElementById("item-list")
  activeTab.classList.add("active")
</script>

app/views/contributions/update.js.erb
function refreshUpdateForm(innerHTML) {
  const supplyCard = document.querySelector("[data-supply-id='<%= @supply.id %>']");
  supplyCard.innerHTML = innerHTML;
  refreshJs(supplyCard);
}
refreshUpdateForm('<%= j render "supply_card", supply: @supply, participation: @participation, contribution: @participation.contributions.find_by(supply_id: @supply.id)%>')