config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    collection do
      get 'dashboard', to: 'users#dashboard', as: :dashboard
    end
  end

  resources :events do
    resources :fees, only: [:create, :index, :update, :destroy]
    get '/:token/invitation', to: 'events#invitation', as: :invitation
    resources :contributions, only: [:index, :create, :destroy, :update]
    resources :participations, only: [:index, :update, :destroy, :create]
    resources :supplies, only: [:index, :create, :update, :destroy]
    resources :fee_contributions, only: [:destroy, :create]
  end
  

  resources :contributions, only: [] do
    post 'change-state', to: 'contributions#change_state'
  end
  

  # static pages
  get "/composants" => "pages#composants"

end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :participation
  has_many :fee_contributions, dependent: :destroy

  validates :cost, presence: true
  validates :cost, numericality: { greater_than_or_equal_to: 2 }

  def price_per_person
    cost / (fee_contributions.size + 1)
  end
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @fee = Fee.new
    authorize @fee
    @fee.cost = params[:cost]
    @fee.participation_id = params[:participation_id]
    @fee.save
    redirect_to event_contributions_path(@event)
  end

  def index
    authorize policy_scope(Fee)
    @event = Event.find(params[:event_id])
    @map_url = @event.map_url
    @agenda_url = @event.agenda_url
    @fees = @event.fees
    @participation = Participation.find_by(user_id: current_user.id, event_id: @event.id)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @fee = Fee.find(params[:id])
    authorize @fee
    @fee.destroy
    redirect_to event_contributions_path(@event)
  end

  def update
    @event = Event.find(params[:event_id])
    @fee = Fee.find(params[:id])
    authorize @fee
    @fee.cost = params[:cost]
    @fee.save
    redirect_to event_contributions_path(@event)
  end
end

app/views/fees/_fee_card.html.erb
<% fee_contribution = participation.fee_contributions.find_by(fee_id: fee.id) %>

<h3><%= fee.participation.user.first_name %> a payé <%= fee.cost %> €</h3>
<p><%= fee.fee_contributions.size %> personnes participent</p>
<p>prix/personne : <%= fee.price_per_person %> €</p>
<% if fee_contribution.nil? %>
  <form action="<%= event_fee_contributions_path(event) %>" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= hidden_field_tag :fee_id, fee.id %>
    <%= hidden_field_tag :participation_id, participation.id %>
    <input type="submit" class="m-0 btn-thin btn-base btn-blue" value="Participer">
  </form>
<% else %>
  <%= link_to event_fee_contribution_path(event, fee_contribution), method: :delete, class: "m-0 btn-thin btn-base btn-red" do %>
    Annuler votre participation
  <% end %>
<% end %>

app/views/fees/index.html.erb
<%= render "shared/navbar", user: current_user %>
<%= render "shared/event_header", event: @event, map_url: @map_url, agenda_url: @agenda_url %>
<div class="container-fees">
<% if @fees.first.nil? %>
  <p>Pas encore de frais...</p>
<% end %>

<% my_fee = @fees.find_by(participation_id: @participation.id) %>
<% unless my_fee.nil? %>
  <div class="fees">
    <h2 class="text-secondary">Vous avez demandé : <br><%= my_fee.cost %> €</h2>
    <p><%= my_fee.fee_contributions.size %> personnes participent</p>
    <p>Prix/personne : <%= my_fee.price_per_person %> €</p>
  </div>
<% end %>

<% unless @participation.fee_contributions.empty? %>
  <div class="btn-green text-light">
    <a class="btn text-light" data-toggle="collapse" href="#my-fees_contr" role="button" aria-expanded="false" aria-controls="my-fees_contr">
      <h3>Je participe aux frais de <%= @participation.fee_contributions.size %> personne(s)</h3>
    </a>
    <div class="container collapse" id="my-fees_contr">
      <% @participation.fee_contributions.each do |fc| %>
        <p>Je dois <%= fc.fee.price_per_person %> € à <%= fc.fee.participation.user.first_name %> <%= fc.fee.participation.user.last_name %></p>
      <% end %>
    </div>
  </div>
<% end %>

<div class="container">
  <% @fees.each do |fee| %>
    <% unless fee == my_fee  %>
      <div class="fee-card">
        <%= render "fee_card", event: @event, fee: fee, participation: @participation %>
      </div>
    <% end %>
  <% end %>

</div>

<script>
  const activeTab = document.getElementById("item-frais")
  activeTab.classList.add("active")
</script>
</div>